### ISSUE TITLE
could you please add the requirement?

### ISSUE THREAD

**Issue by mengyingzhou** [PengjieRen/RepeatNet#2]
Hi!
Thank you for the awesome work.
Since the dependency packages have updated, could you please add the requirement.txt for the detailed package version information?

thx
mengying

**Comment by PengjieRen** [comment]
Hi,
please refer to the pytorch version, which is much faster: https://github.com/PengjieRen/RepeatNet-pytorch. 
Thanks!

**Comment by mengyingzhou** [comment]
got, thx!
